
image:
  repository: ghcr.io/platformbuilds/cosmolet
  tag: v0.1.0
config:
  loopIntervalSeconds: 15
  bgp:
    asn: 65101
  frr:
    ensureStatic: true
securityContext:
  privileged: true
daemonset:
  hostNetwork: true
