
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cosmolet
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cosmolet
  namespaceSelector:
    matchNames: ["kube-system"]
  endpoints:
    - port: http-metrics
      interval: 30s
