
image:
  repository: ghcr.io/platformbuilds/cosmolet
  tag: latest
  pullPolicy: IfNotPresent

config:
  loopIntervalSeconds: 30
  bgp:
    asn: 65001
  frr:
    ensureStatic: true

securityContext:
  privileged: true

daemonset:
  hostNetwork: true
  hostPID: true
  nodeSelector: {}
  tolerations: []

rbac:
  create: true
serviceAccount:
  create: true
  name: ""
