
apiVersion: v1
kind: Service
metadata:
  name: web-cluster
  namespace: demo
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector: { app: web }
  ports:
  - name: http
    port: 80
    targetPort: 8080
