
name: Release

on:
  push:
    tags:
      - 'release/mark-v*'

permissions:
  contents: write
  packages: write

env:
  RAW_TAG: ${{ github.ref_name }}                               # e.g., release/mark-v1.2-3
  VERSION: ${{ github.ref_name && replace(github.ref_name, 'release/mark-', '') }}  # e.g., v1.2-3

jobs:
  approval:
    if: ${{ github.triggering_actor == github.repository_owner }}
    runs-on: ubuntu-latest
    environment: release
    steps:
      - run: echo "Release gated by environment approval."

  build_binaries:
    if: ${{ github.triggering_actor == github.repository_owner }}
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build multi-arch binaries (Makefile)
        run: make build-multi

      - name: Create GitHub Release (idempotent)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RAW_TAG }}
          name: Cosmolet ${{ env.VERSION }}
          generate_release_notes: true

      - name: Upload binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RAW_TAG }}
          files: |
            dist/cosmolet-*

  docker_multiarch:
    if: ${{ github.triggering_actor == github.repository_owner }}
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute lowercase image repo
        run: echo "IMAGE_REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build & Push multi-arch image (Makefile)
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REPOSITORY: ${{ env.IMAGE_REPO_LC }}
          IMAGE_TAGS: ${{ env.VERSION }},${{ env.RAW_TAG }}
          PLATFORMS: linux/amd64,linux/arm64
        run: make docker-buildx
